### ISSUE TITLE
CMR for delay because of training

### ISSUE THREAD

**Issue by cleliameneghin** [berufsbildung-basel/awmps#10]
- [x] create CMR and submit it to DJ
- [ ] update Grant chart in Miro
- [x] get signatue from DJ
- [x] sign it yourself
- [x] add CMR to change managment documentation in the wiki

**Comment by martinst06** [comment]
[CHANGE_REQUEST_FORM_SIGNED.pdf](https://github.com/berufsbildung-basel/awmps/files/12647988/CHANGE_REQUEST_FORM_SIGNED.pdf)
