### ISSUE TITLE
Decide for a Color scheme from the color palette

### ISSUE THREAD

**Issue by cleliameneghin** [berufsbildung-basel/awmps#13]
- [x] Make 2 different blank options
- [x] Make 2 similar options each
- [x] Play with borders, shadows, forms
- [x] Let customer choose button, box, etc.
- [x] Choose 1 blank option that I like and think fits best
- [x] Choose 2 colors to work with from the color palette
- [x] Make a light and a dark version based on those colors
- [x] Apply that same color to all pages
- [x] Receive feedback form the customer

**Comment by martinst06** [comment]
##

 2 Blanks

![Image](https://github.com/berufsbildung-basel/awmps/assets/132879041/e97c9f96-b790-4def-aa78-6c78a82fc818)


## +2 similar blank options each

![Image](https://github.com/berufsbildung-basel/awmps/assets/132879041/921334d5-8581-4d36-a5d1-5620a02bf88f)

![Image](https://github.com/berufsbildung-basel/awmps/assets/132879041/e81be0f0-a245-4822-b366-85eaca7dd2df)


## different options (borders, shadows, forms, gauges) for objects (button, box, bar)

# Gauges

![Image](https://github.com/berufsbildung-basel/awmps/assets/132879041/1097e008-844b-4188-aff4-2c5bc42dd554)

# Button

![Image](https://github.com/berufsbildung-basel/awmps/assets/132879041/779f1aa2-7681-4c40-bdb4-929583ff491f)

# Bars

![Image](https://github.com/berufsbildung-basel/awmps/assets/132879041/5d3faea7-4219-44a5-b5a7-a80d9664d53c)


## Colors of choice:

# Blue:

#Light blue

![Image](https://github.com/berufsbildung-basel/awmps/assets/132879041/09b44a8d-a96e-41db-b056-5cd14b58220b)

# dark blue

![Image](https://github.com/berufsbildung-basel/awmps/assets/132879041/d7925a53-7885-4583-85c7-5fb6a15fdadb)

# Green:

#Light green

![Image](https://github.com/berufsbildung-basel/awmps/assets/132879041/c681570b-86dc-41f1-81f6-a76add609133)


# Dark green

![Image](https://github.com/berufsbildung-basel/awmps/assets/132879041/bfe4fe9e-cd8d-494b-ba8b-2d88901fb87d)


## All Pages:

- https://xd.adobe.com/view/db7ec154-bab0-4745-849d-686bd281c099-8e2d/
