### ISSUE TITLE
Provide Logo and Color scheme

### ISSUE THREAD

**Issue by cleliameneghin** [berufsbildung-basel/awmps#15]

**Comment by solaris007** [comment]
Background palette: https://coolors.co/palette/e9f5db-cfe1b9-b5c99a-97a97c-87986a-718355
Stats / Gauge / Widget palette: https://coolors.co/palette/f94144-f3722c-f8961e-f9844a-f9c74f-90be6d-43aa8b-4d908e-577590-277da1

Choose appropriate font colors (make suggestions to me)
