### ISSUE TITLE
send all NUC parts to jose

### ISSUE THREAD

**Issue by t0risutan** [berufsbildung-basel/awmps#37]
- [x] Research different Intel NUCs
- [x] Research different 2TB NVMe SSDs
- [x] Research Memory
- [x] Choose compatible NUC , SSD and Memory

**Comment by martinst06** [comment]
[NUC](https://www.digitec.ch/en/s1/product/intel-nuc-13-pro-kit-nuc13anhi7-core-i7-1360p-barebones-24945540?gclid=Cj0KCQjwgNanBhDUARIsAAeIcAuLTXwco_77BYSNdArCiNKXzHKT-AvZjWUw4D8MWDjpActxEnNKZaoaAmD4EALw_wcB&gclsrc=aw.ds)

[SSD](https://www.brack.ch/wd-black-ssd-sn770-m-2-nvme-2000-gb-1323943?utm_source=google&utm_medium=cpc&utm_campaign=%21cc-pssh%21l-d%21e-g%21t-pla%21k1-it%21z-it_multimedia_channable&utm_term=&adgroup_id=161560923588&ad_type=pla&prod_id=1323943&campaign_id=9422718872&gclid=Cj0KCQjwgNanBhDUARIsAAeIcAuTxB5r3JegpYzU6qhMc226CEQaQS5bpyO-CyREicpzGbz1YkdOZeYaAipWEALw_wcB&hc_fcv=ZPWRTQKYAtRlHR5N~NDKFHHM5IF72vk0Izzzzzzzz~NDKFHFs18hkhCE4lzzzzzzzz) or [SSD](https://www.digitec.ch/en/s1/product/wd-black-sn770-2000-gb-m2-2280-ssd-18756199)

[Memory](https://www.digitec.ch/de/s1/product/crucial-laptop-memory-1-x-16gb-3200-mhz-ddr4-ram-so-dimm-ram-13913198?gclid=Cj0KCQjwgNanBhDUARIsAAeIcAvDCQ8x2eZOQ1yG0LOFUT8JlFrKfqhW-A0ZOvcqcQ7f1RN_vLonC6oaArrlEALw_wcB&gclsrc=aw.ds)
