### ISSUE TITLE
Creation of Quotes

### ISSUE THREAD

**Issue by cleliameneghin** [berufsbildung-basel/awmps#7]
How expensive the different proposals are with an itemized list
including :

- [x] water hose or tube
- [x] sensors
- [x] microcontrollers
- [x] servers
- [x] wires
- [x] valves
- [x] connectors
- [x] flow meters
- [x] show quote to customer
- [x] betriebskosten
- [x] Raspberry Pi Starter 8GB Kit instead of Raspberry Pi 4GB
- [x] Raspberry Pi and NUC as single units
- [x] Remove USB C Charger and Power Supply from list
- [x] Group the Sensors / sub divide them in ambient and plant specific sensors
- [x] Split in miscellaneous and irrigation
- [x] subtotal for hardware as a whole without product
- [x] get signoff on 1 quote from customer

**Comment by martinst06** [comment]
![Image](https://github.com/berufsbildung-basel/awmps/assets/132879041/1ad4df3c-c1cf-41ae-9190-786dfe3b72f4)


![Image](https://github.com/berufsbildung-basel/awmps/assets/132879041/23c7a3c0-9964-4936-868f-0a09086189be)
